### PR TITLE
python/win32: Manually set the python home directory to where the dll…

### PR DESCRIPTION
**Pull request by learn-more**
… is loaded from.

### CODE REVIEW

**Comment by TingPing** [comment]
@Arnavion Does this look reasonable to you?

**Comment by learn-more** [comment]
@Arnavion  could you please have a look at this?

**Comment by Arnavion** [comment]
`#include <Windows.h>` instead of `__declspec(dllimport)`

Put the calls to `GetModuleFileNameA/W` and `strchr/wcschr` inside `#ifdef PY_3K` instead of defining new macros for them.

And what exactly is this fixing?

**Comment by learn-more** [comment]
This fixes python failing to initialize, because it cannot find the base dir if it is not in the path.

**Comment by learn-more** [comment]
The requested changes have been made, and it fixed python 3.6 not working for someone else in irc today.
```
[1838:50] <torhu> Python 2 works, 3.6 fails during initialization of Python, then crashes
[1840:04] <mjansen> windows?
[1840:46] <torhu> yes
[1841:45] <torhu> traceback https://pastebin.com/3vwawvJ3
[1845:44] <mjansen> torhu: https://github.com/hexchat/hexchat/pull/1987
[1845:49] <mjansen> can you test a build from that?
[1846:36] <torhu> yes, when I'm back, in a bout an hour
[1900:34] <mjansen> no rush
[1900:36] <mjansen> this is irc ;)
[2016:17] <torhu> Client: HexChat 2.12.4 • OS: Microsoft Windows 10 Pro (x64) • CPU: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (2.60GHz) • Memory: 5.8 GiB Total (2.2 GiB Free) • Storage: 385.8 GiB / 465.3 GiB (79.5 GiB Free) • VGA: NVIDIA GeForce GT 630M, Intel(R) HD Graphics 4000 • Uptime: 1d 22h 5m 17s
[2024:38] <torhu> oh, didn't know it would post that...
[2026:03] <torhu> mjansen: ^
[2026:07] <torhu> thanks
[2040:04] <mjansen> so it fixed the crash i guess?
[2040:16] <torhu> seems so
```

**Comment by torhus** [comment]
Maybe this is only an issue if you have both Python 2.x and 3.x installed? Funny thing is, my Python 3 installation comes first in the PATH so I'm not sure why that was the one that failed to initialize.

**Pull request closed without merging**
