### PR TITLE
Fix selection when part of the selected text is above/below a border.

### PR DESCRIPTION
**Pull request by RichardHitt**
Also, fix problems uncovered by static analysis.
Basically this fix amounts to a rewrite of gtk_xtext_selection_draw().

### CODE REVIEW

**Comment by TingPing** [comment]
You mentioned on IRC that these changes will be irrelevant with the next pull request you plan.

**Comment by RichardHitt** [comment]
Yes, I used this as a base for my 546 work, and that work will affect just about everything in xtext.c.  Thanks.  Maybe realistically a month or two and I'll have an alpha version, but I'm already using it and I'm pleased with how it looks.

**Comment by RichardHitt** [comment]
I mistakenly included three commits Feb 18.  Getting rid of them and I'll retest and resubmit the pull request.

**Comment by Stanzilla** [comment]
@RichardHitt are you still planning on making a new PR?

**Comment by RichardHitt** [comment]
Hi, Benj

Not really, yet.  I'm just adding commit after commit to the existing 
one, as tomek finds and I fix problems with it.  Are you as a user 
actively interested in the problem and its solution?  I'd love to hear 
your comments.

Richard

**Comment by Stanzilla** [comment]
@RichardHitt I'm personally more interested in https://github.com/hexchat/hexchat/issues/546 and https://github.com/hexchat/hexchat/issues/591 but I figured I'd ask here as this was the last thing I saw you working on and figured it might involve some rewriting of xtext and could include parts of those other issues.

**Comment by RichardHitt** [comment]
Hi, Benj

Well, I haven't worked on 546 for some time, trying to get all the nooks 
and crannies of that 1261 straightened out, and then there are a couple 
of other important xtext.c-related things to do (1389 and 
non-English-alphabet performance) that in my ho deserve to be attacked 
first.

But I just now retested my 546PreAlpha and it seems still to be 
buildable.  Use this command to fetch it:

	git clone -b 546PreAlphahttp://github.com/RichardHitt/hexchat  <https://github.com/RichardHitt/hexchat>

In certain situations the rendering is not perfect, but I believe you'll 
be happy if what you want is message spacing.  I think it looks nice. (I 
know that mIRC calls it "paragraph" spacing, but it seems to me that the 
distinction is better conveyed by the words "line" and "message" than 
"line" and "paragraph".  What do you think?)

See also the issues/546 comments dated Mar 3.

Richard

**Comment by Stanzilla** [comment]
Oh I guess I don't really have a build env set up but I can try!

**Comment by RichardHitt** [comment]
Hi Benj

Well, I could build one for you.  What OS are you running?  I'm running 
Fedora myself, various releases.  If you're on windows, you could use 
the .exe I built, at "http://rbh00.dyndns.org/~rbh00/546/HexChat 2.11.0 
x86.exe"  If I recall correctly, you would need, once you've installed 
and started it, to use this command to get message spacing:  /set 
text_spacing_msg 3

Richard

**Comment by Stanzilla** [comment]
Yep, Windows, your link worked fine and I tested it and it actually looks pretty good! One thing though, can I also increase the spacing between the most recent line in chat and the input box?

**Comment by Stanzilla** [comment]
Ok sometimes it bugs out and shows no text at all, I can highlight random stuff though

**Comment by Stanzilla** [comment]
Made a gif instead:

**Comment by RichardHitt** [comment]
Hi Benj

Thanks for the gif!  I guess your last three messages to me were not 
about 1261 but 546, too bad they ended up at issues/1261.  (If I'm wrong 
then I'm more confused than usual!)  As to more space right before the 
input window, Yeah it's possible.  With the former fixed-height lines 
all you'd need to do would be a simple resize, but of course now with my 
546 work that wouldn't be satisfactory; I'd have to add Yet Another 
Option™, and option proliferation isn't a good thing for teeny tiny 
effects like that.  Still, I could simply always insist on at least 
text_spacing_msg units of height as blank space at the very bottom of 
the text window.

I presume your gif was taken with respect to 546 and not 1261, right?  
Yet looking at its frames I don't see hardly any mujlti-line messages 
and the ones I do see don't have extra spacing.  So, reassure me that 
the gif shows your running of 546PreAlpha, or set me straight.  Thanks.

Richard

**Comment by Stanzilla** [comment]
The gif was taken on 546, sorry if I confused you :)

**Pull request closed without merging**
