### PR TITLE
Spelling: SOCKS5, Byte per second

### PR DESCRIPTION
**Pull request by comradekingu**
As per https://en.wikipedia.org/wiki/SOCKS

### CODE REVIEW

**Comment by TingPing** [comment]
This is also spelled incorrect in `setup.c` I believe.

**Comment by comradekingu** [comment]
@TingPing Looked a bit like it would start breaking things. Also changed to "Byte per second" for referencing the unit of measure.

**Comment by TingPing** [comment]
Is `bytes per seconds` actually wrong? It sounds better to me and I see it widely in use.

**Comment by comradekingu** [comment]
@TingPing I think one is the unit of measure and the other is actual use when it is beyond 1.

**Pull request merged**
