### PR TITLE
Prevent loading a Lua script if it's already loaded

### PR DESCRIPTION
**Pull request by culb**
Prevent loading a Lua script if it's already loaded

### CODE REVIEW

**Comment by TingPing** [comment]
Need rebase.

**Comment by culb** [comment]
I did. I'm not sure what the problem is.

**Comment by TingPing** [comment]
```sh
git remote add upstream https://github.com/hexchat/hexchat.git
git checkout LuaPreventMultiLoad
git pull --rebase upstream master

# Now that it is up to date, remove all the other trash
git rebase --interactive HEAD~10

# Just delete every commit other than the one
# Do the same for your other branches.
```

**Comment by culb** [comment]
I wasn't 100% complete with the commands I used. Thank you.

**Comment by TingPing** [comment]
You have to actually push anything you rebased, `git push -f origin LuaPreventMultiLoad`

**Comment by culb** [comment]
Oh, I see.

**Pull request closed without merging**
