### PR TITLE
Fix incorrect translations such as なると

### PR DESCRIPTION
**Pull request by titsuki**
Hi, I found some incorrect translations.

For example: 
+ "なると" means food (c.f., https://ja.wikipedia.org/wiki/鳴門巻き) and doesn't make sense in a context of IRC.
+ "略奪" (Note: Maybe mistakenly "奪略" was used) is often used in a context of war but not used in a context of a privilege control feature.

### CODE REVIEW

**Comment by TingPing** [comment]
All translations are handled here: https://www.transifex.com/hexchat/

**Comment by titsuki** [comment]
@TingPing Thanks for your reply! I didn't noticed such a page by my oversight.

**Comment by TingPing** [comment]
If you make an account there just let me know and I'll add you to the language where you can just make any changes.

**Comment by titsuki** [comment]
@TingPing Sorry for the late reply. I already sent a request to join the team about two days ago.

**Comment by TingPing** [comment]
Added

**Pull request closed without merging**
