### PR TITLE
thememan: Check for portable-mode file in the application directory.

### PR DESCRIPTION
**Pull request by learn-more**
Fix for #1902

### CODE REVIEW

**Comment by TingPing** [comment]
Please include `Fixes #1902` in the commit message body.

**Comment by learn-more** [comment]
I was not sure if that was allowed, will do in the revised commit.
Need to research why mono doesn't like this.

**Comment by Arnavion** [comment]
Too old to support `?.` probably.

**Comment by learn-more** [comment]
Good point @Arnavion

**Pull request merged**
