### PR TITLE
Windows 10 ID

### PR DESCRIPTION
**Pull request by ElPumpo**
Added windows 10 id.

### CODE REVIEW

**Comment by TingPing** [comment]
Do you have a hidpi monitor and does everything work perfectly for you? Another user had reported such but it doesn't really make sense. GTK2 is certainly not actually DPI aware on any platform unless it happens to 'just work' on win32 which my understanding was that wouldn't be true.

**Comment by ElPumpo** [comment]
Yeah I got a hidpi monitor, and gtk2 doesn't have to be dpi aware. 
If you could compile a version that is dpi aware I would like to try it out.

**Comment by TingPing** [comment]
> Yeah I got a hidpi monitor, and gtk2 doesn't have to be dpi aware. 

So everything in hexchat is super small for you then?

> If you could compile a version that is dpi aware I would like to try it out.

It isn't and never will be DPI aware.

**Comment by ElPumpo** [comment]
No, not everything is super small.

The automatic Windows font scaler only works up to 100% size at a 1440p res on Windows display settings.
Indicating that the application is DPI aware it will by itself scale the font so Windows doesn't wash out the fonts by trying to make them look good.

ATM the application has tiny and washed out fonts.
I've used DPI aware on my personal applications with success.

If you could build a version that is DPI aware and send it to me so I can test the application myself on a hidpi monitor it would be great. I'll give you screenshots to compare too.

If you're never making your application DPI aware hidpi display users will have to look another direction.

**Comment by TingPing** [comment]
> If you're never making your application DPI aware hidpi display users will have to look another direction.

That's not up to hexchat; Gtk2 is the toolkit used for the application and it is no longer actively getting new features such as hidpi support.

**Comment by ElPumpo** [comment]
Oh, I understand. Is there a possibility to upgrade from Gtk2 to Gtk3 without chaning major code, as Gtk 3.10 added hidpi support?

**Comment by DoctorWho11** [comment]
Regardless, there would need some changes as a lot of gtk2 api has been deprecated. And the xtext widget would need to be updated to make use of cairo drawing.

**Comment by ElPumpo** [comment]
Yeah, upgrading from Gtk2 to Gtk3 isn't going to be a switch.

Anyways I found a fix:
1. Right click hexchat.exe and press properties
2. On the compatibility tab there is a "disable scaling at high DPI" (i'm on a Swedish OS, using sence-translate). Check the button and restart the client.

 Works great now! I've done this with a lot of applications like Steam and Spotify; works great!

But still official HidPI support would be better.

**Comment by TingPing** [comment]
This was done in https://github.com/hexchat/hexchat/commit/e40fbee772f13abb125e47cd7a1525689756ae11

**Pull request closed without merging**
