### PR TITLE
Support for older libnotify versions

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by TingPing** [comment]
Curious what distribution has libnotify 0.6.0 (2011) but also has glib 2.34.0+ (2012)?

**Comment by mtelka** [comment]
[OpenIndiana Hipster](http://www.openindiana.org/overview/the-hipster-branch/), currently with glib 2.43.4 and libnotify 0.4.5.

**Comment by TingPing** [comment]
Those are quite the odd package versions, a 7yo libnotify and a year old development release of glib... but fair enough

**Comment by TingPing** [comment]
Merged as 54c6418d619e1ec96166f9fabb426f011068de99

**Pull request closed without merging**
