### PR TITLE
SCRAM: Small bugfixes

### PR DESCRIPTION
**Pull request by patrick-irc**
A few improvements requested by Nei. They are not finish yet, so I keep this PR as draft.

### CODE REVIEW

**Comment by TingPing** [comment]
This does need rebasing on master (`git pull --rebase origin master`)

**Comment by ircnet-com** [comment]
> This does need rebasing on master (`git pull --rebase origin master`)
Is it ok now? I had some conflicts when I tried to rebase. So I have created a new branch from current master, cherry-picked and force-pushed.

**Comment by patrick-irc** [comment]
>This does need rebasing on master (git pull --rebase origin master)

Is it ok now? I had some conflicts when I tried to rebase. So I have created a new branch from current master, cherry-picked and force-pushed.

**Comment by TingPing** [comment]
Looks good.

**Comment by patrick-irc** [comment]
Ready to be merged now.

**Pull request merged**
