### PR TITLE
Update es.po

### PR DESCRIPTION
**Pull request by hardvk0**
Multiple corrections

### CODE REVIEW

**Comment by TingPing** [comment]
Translations are handled on https://www.transifex.com/hexchat/hexchat/

**Comment by hardvk0** [comment]
> Translations are handled on https://www.transifex.com/hexchat/hexchat/
transifex is blocked for translation in English

**Comment by TingPing** [comment]
You have to request access but it is there.

**Comment by hardvk0** [comment]
Yes, but it is 100% reviewed, I can not modify it. The current translation is very bad, it seems like a machine translation.

**Comment by TingPing** [comment]
I will add you as a reviewer, what is your username there?

**Comment by hardvk0** [comment]
I am hard_ware

**Comment by TingPing** [comment]
Done. You should be able to modify them now.

**Comment by hardvk0** [comment]
Thanks, hope this pleases everyone.

**Pull request closed without merging**
