### PR TITLE
Added MHOP command

### PR DESCRIPTION
**Pull request by d-browne**
Noticed that there is no MHOP command. Given that there is a MOP, MDEOP and MDEHOP it seems like the useful MHOP command is missing. I have added it in.

### CODE REVIEW

**Comment by TingPing** [comment]
Half op is not universally supported and AFAIK none of the other built in commands apply to half-op so I'm not sure we should start now. A script could ofc trivially do this.

**Comment by d-browne** [comment]
Thank you TingPing. There are actually three built in half-op commands already. HOP, DEHOP and MDEHOP. The only one that is missing is MHOP which is why I thought it appropriate to add. Especially given that MDEHOP is already there.

**Comment by TingPing** [comment]
Ah so there is. Another question is when is mass oping even wanted?

**Comment by d-browne** [comment]
The three situations I've needed mass oping and hoping have usually been related to: the creation of new channels and quickly oping the founders/channel bots; initializing channel wide ops for all-op channels; and channel festivities/games.

Funnily enough two people in one of my channels noticed the mhop feature missing from hexchat at the same time, shortly after trying to restore the channel wide half ops after a mdehop. That inspired me to head over here :]

**Comment by TingPing** [comment]
> (needs chanop)

Can't a halfop halfop other users?

**Comment by kernelpanic3** [comment]
No, they cannot (at least that's the way it is on all the networks I've been on).

**Pull request merged**
