### PR TITLE
.travis.yml: use container-based infrastructure

### PR DESCRIPTION
**Pull request by Mikaela**

### CODE REVIEW

**Comment by Mikaela** [comment]
Sorry for force-pushes, too tired and didn't first realize that

1. I didn't restore notifications.
2. I didn't remove the old apt-commands.

This list is based on `apt-rdepends --build-depends --follow=DEPENDS xchat` and the ones originally installed, I will now go take a look at those whitelist policies.

**Comment by TingPing** [comment]
BTW there is an official hexchat package now so you can look at its build deps.

**Comment by TingPing** [comment]
HexChat does not depend on libgtkspell-dev.

**Comment by Mikaela** [comment]
XChat depedencies replaced with HexChat ones.

**Comment by paladox** [comment]
Shoulden xchat or hexchat be in the packages.

**Comment by Mikaela** [comment]
> Shoulden xchat or hexchat be in the packages.

Neither is used for compiling HexChat.

**Comment by TingPing** [comment]
@Mikaela Looks like we need the `mono-devel` package.

**Comment by Mikaela** [comment]
Ready for merge! :)

**Comment by TingPing** [comment]
Merged as https://github.com/hexchat/hexchat/commit/edd57fdc868c2547a182705ffbf478ea4134169d

**Pull request closed without merging**
