### PR TITLE
Updated translation

### PR DESCRIPTION
**Pull request by Felipefpl**
Updated translation to brazilian portuguese.

### CODE REVIEW

**Comment by TingPing** [comment]
Translations are all handled on Transifex rather than Github PRs, see https://hexchat.readthedocs.io/en/latest/helping.html#translation

**Comment by Felipefpl** [comment]
Ok, thanks for the info, i signed there and i'm waiting to be added.

**Comment by TingPing** [comment]
Accepted.

**Comment by Felipefpl** [comment]
Thanks for that but now i have another problem, more than 93% of the translation is marked as reviewed by a previous translator who did his work more than 3 years ago, because of that i cant add the hundreds of fixes i made to the translation unless someone removes the reviewed status.

**Comment by TingPing** [comment]
I've changed your permissions so you should be able to make changes.

**Comment by Felipefpl** [comment]
> I've changed your permissions so you should be able to make changes.

Thank you very much for this, i went ahead and removed the "reviewed" status from the translation, i'm gonna let stay that so the translators may make their changes without any problems in the future. :)

**Pull request closed without merging**
