### PR TITLE
Update io.github.Hexchat.desktop.in.in 07/25/2022

### PR DESCRIPTION
**Pull request by marcelocripe**
io.github.Hexchat.desktop.in.in file update on 07/25/2022

Multi-language translation.
The languages that have not been credited, have been translated with internet translation services and need to be proofread or corrected by native speakers of the respective languages.

- - - - -

Atualização do arquivo io.github.Hexchat.desktop.in.in 25/07/2022

Tradução de vários idiomas.
Os idiomas que não foram creditados, foram traduzidos com os serviços de tradução da internet e precisam ser revisados ou corrigidos por falantes nativos dos respectivos idiomas.

### CODE REVIEW

**Comment by TingPing** [comment]
This isn't where the translations belong. They are in `/po` and are handled on https://www.transifex.com/hexchat/hexchat/

**Comment by marcelocripe** [comment]
Hello TingPing.

Thank you so much for responding to my merge request.
Please, could you tell me what are the numbers of Transifex entries that are used to create the HexChat .desktop file? In the .po file there is no comment from the programmer about which texts will be used in Name, GenericName, Comment and Keywords.

I made the request to join the team http://www.transifex.com/hexchat/hexchat/language/pt_BR/, I'm waiting for approval, if you are an administrator or coordinator, you can approve my request.

The pt_BR texts need revision and some specific improvements, as well as attention to the texts that are used in the HexChat .desktop file.

Currently the number of languages ​​covered in HexChat is much less than the number of languages ​​we are working on in the antiX Linux community. At this URL https://gitlab.com/antix-contribs/antix-desktop-files you will find our ongoing volunteer work.

Thank you very much.

- - - - -

Olá TingPing.

Muito obrigado por responder ao meu pedido de mesclagem.
Por favor, você saberia me informar quais são os números das entradas do Transifex que são utilizadas para criar o arquivo .desktop do HexChat? No arquivo .po não há comentário do programador sobre quais textos serão utilizados em Name, GenericName, Comment e Keywords.

Eu fiz o pedido para me juntar a equipe http://www.transifex.com/hexchat/hexchat/language/pt_BR/, eu estou aguardando a aprovação, caso você seja um administrador ou coordenador, você poderá aprovar o meu pedido.

Os textos pt_BR precisam de revisão e algumas melhorias pontuais, além de uma atenção aos textos que são utilizados no arquivo .desktop do HexChat.

Atualmente a quantidade de idiomas coberto no HexChat é bem menor que a quantidade de idiomas que estamos trabalhando na comunidade antiX Linux. Neste URL https://gitlab.com/antix-contribs/antix-desktop-files você encontrará o nosso trabalho voluntário que está em andamento. 

Muito obrigado.

**Comment by TingPing** [comment]
> In the .po file there is no comment from the programmer about which texts will be used in Name, GenericName, Comment and Keywords.

This is unfortunate. We could add those comments to the desktop file still.

> I'm waiting for approval, if you are an administrator or coordinator, you can approve my request.

I have added you.

> Currently the number of languages ​​covered in HexChat is much less than the number of languages ​​we are working on in the antiX Linux community. At this URL https://gitlab.com/antix-contribs/antix-desktop-files you will find our ongoing volunteer work.

If there are individuals you'd like to add for specific languages I'll gladly add them.

**Comment by marcelocripe** [comment]
#I have added you.
Thanks!

#If there are individuals you'd like to add for specific languages I'll gladly add them.
What we have at the moment is just the .desktop file that has the native revision of 6 or 7 languages, all the others are automatic translations that we get with the internet translation services.

#This is unfortunate. We could add those comments to the desktop file still.
Transifex accepts to receive comments from the programmer, in the code of the .pot or .po file, insert "#." (the sharp followed by a period) before the entries to be translated. In this way the instructions are displayed to all translators.

Thanks.

- - - - -

#I have added you.
Obrigado!

#If there are individuals you'd like to add for specific languages I'll gladly add them.
O que nós temos no momento é apenas o arquivo .desktop que possui a revisão de nativos de 6 ou 7 idiomas, todos os outros são traduções automáticas que obtivémos com os serviços de tradução da internet.

#This is unfortunate. We could add those comments to the desktop file still.
O Transifex aceita receber comentários do programador, no código do arquivo .pot ou .po deve ser inserido "#." (o sustenido seguido de um ponto) antes das entradas a serem traduzidas. Desta forma as instruções são exibidas para todos os tradutores.

Obrigado.

**Comment by marcelocripe** [comment]
Hello TingPing.
Could you please tell me which are the http://www.transifex.com/hexchat/hexchat/language/pt_BR/ entries of the texts that are used in the HexChat .desktop file?
Thanks.

- - - - -

Olá TingPing.
Por favor, você poderia me informar quais são as entradas do http://www.transifex.com/hexchat/hexchat/language/pt_BR/ dos textos que são utilizados no arquivo .desktop do HexChat?
Obrigado.

**Comment by TingPing** [comment]
In the filter type: `occurrence:data/misc/io.github.Hexchat.desktop.in.in`

**Comment by marcelocripe** [comment]
> In the filter type: occurrence:data/misc/io.github.Hexchat.desktop.in.in
TingPing This information is not available on Transifex. Also, this information does not specify which text will be used in the input "Name", "GenericName", "Comment" and "Keywords".

- - - - -

> In the filter type: occurrence:data/misc/io.github.Hexchat.desktop.in.in
TingPing esta infomação não está disponível no Transifex. e ainda, esta infomação não especifica qual texto será utilziado na entrada "Name", "GenericName", "Comment" e "Keywords".

**Comment by TingPing** [comment]
> TingPing this information is not available in Transifex, and yet, this information does not specify which text will be used in the input "Name", "GenericName", "Comment" and "Keywords".

Somebody needs to add comments to the file for that.

**Comment by marcelocripe** [comment]
"Somebody needs to add comments to the file for that."

The file https://github.com/hexchat/hexchat/blob/master/po/ has:

#: data/misc/io.github.Hexchat.appdata.xml.in:4
#: data/misc/io.github.Hexchat.appdata.xml.in:5
#: data/misc/io.github.Hexchat.desktop.in.in:3
msgid "HexChat"
msgstr " "

#: data/misc/io.github.Hexchat.appdata.xml.in:9
#: data/misc/io.github.Hexchat.desktop.in.in:4
msgid "IRC Client"
msgstr " "

#: data/misc/io.github.Hexchat.desktop.in.in:5
msgid "Chat with other people online"
msgstr " "

#: data/misc/io.github.Hexchat.desktop.in.in:6
msgid "IM;Chat;"
msgstr " "

#: data/misc/io.github.Hexchat.desktop.in.in:8
#: data/misc/io.github.Hexchat.ThemeManager.desktop.in:5
msgid "hexchat"
msgstr " "


#: data/misc/io.github.Hexchat.desktop.in.in:19
msgid "Open Safe Mode"
msgstr " "

#: data/misc/io.github.Hexchat.ThemeManager.desktop.in:3
msgid "HexChat Theme Manager"
msgstr " "

The comment that starts on the "#:" line has references that are likely to be useful to programmers, but do not specify the correct location of the HexChat ".desktop" file entry and do not guide translators as to where each text entry will be used. .

- - - - -

"Somebody needs to add comments to the file for that."

O arquivo https://github.com/hexchat/hexchat/blob/master/po/ possui:

#: data/misc/io.github.Hexchat.appdata.xml.in:4
#: data/misc/io.github.Hexchat.appdata.xml.in:5
#: data/misc/io.github.Hexchat.desktop.in.in:3
msgid "HexChat"
msgstr " "

#: data/misc/io.github.Hexchat.appdata.xml.in:9
#: data/misc/io.github.Hexchat.desktop.in.in:4
msgid "IRC Client"
msgstr " "

#: data/misc/io.github.Hexchat.desktop.in.in:5
msgid "Chat with other people online"
msgstr " "

#: data/misc/io.github.Hexchat.desktop.in.in:6
msgid "IM;Chat;"
msgstr " "

#: data/misc/io.github.Hexchat.desktop.in.in:8
#: data/misc/io.github.Hexchat.ThemeManager.desktop.in:5
msgid "hexchat"
msgstr " "


#: data/misc/io.github.Hexchat.desktop.in.in:19
msgid "Open Safe Mode"
msgstr " "

#: data/misc/io.github.Hexchat.ThemeManager.desktop.in:3
msgid "HexChat Theme Manager"
msgstr " "

O comentário que é iniciado na linha "#:" possui referências que provavelmente são úteis para os programadores, mas não especificam o local correto da entrada do arquivo ".desktop" do HexChat e não orientam os tradutores sobre onde cada entrada de texto será utilizada.

**Comment by TingPing** [comment]
I think you can add comments direcly in this file: https://github.com/hexchat/hexchat/blob/master/data/misc/io.github.Hexchat.desktop.in.in#L3

```ini
# translators: Name property
Name=HexChat
```

I have not tested this though.

**Comment by marcelocripe** [comment]
"I think you can add comments directly in this file: https://github.com/hexchat/hexchat/blob/master/data/misc/io.github.Hexchat.desktop.in.in#L3"

Hello TingPing.

I prefer to send you here my suggestions for the texts of the comments of the translatable entries.
As I am not a native English speaker and I still rely on automatic internet translators to communicate, I ask you to check the comments texts which are automatic translations from my language to English language (en_US). Please modify the text of the comments as you see fit.
The other suggestion is to sort the untranslatable entries in alphabetical order and leave the translatable entries after the untranslatable entries.

I hope you like my suggestions.

- - - - -

"I think you can add comments directly in this file: https://github.com/hexchat/hexchat/blob/master/data/misc/io.github.Hexchat.desktop.in.in#L3"

Olá TingPing.

Eu prefiro te enviar aqui as minhas sugestões dos textos dos comentários das entradas traduzíveis.
Como eu não sou um nativo do idioma Inglês e ainda dependo dos tradutores automáticos da internet para me comunicar, eu peço a você para conferir os textos dos comentários que são traduções automáticas do meu idioma para o idioma Inglês (en_US). Por favor, modifique o texto dos comentários como você achar melhor.
A outra sugestão é de organizar as entradas não traduzíveis em ordem alfabética e deixar as entradas traduzíveis após as entradas não traduzíveis.

Eu espero que você goste das minhas sugestões.
[io.github.Hexchat.desktop.txt](https://github.com/hexchat/hexchat/files/9268011/io.github.Hexchat.desktop.txt)

**Pull request closed without merging**
