### PR TITLE
 Notification: Implement notification option for channels

### PR DESCRIPTION
**Pull request by BakasuraRCE**
Hi @TingPing,

I implemented the flow of notifications for channels as we accorded:

Flow:

1. You can control the notifications in a global environment
2. chanopts per each channel/pm/network MUST be followed overloading any other setting

Related: https://github.com/hexchat/hexchat/issues/876 https://github.com/hexchat/hexchat/issues/1172

Regards.

### CODE REVIEW

**Comment by aminvakil** [comment]
@BakasuraRCE Could you please rebase your branch with base branch?

**Comment by csomh** [comment]
Hey @BakasuraRCE :wave: Will you have time for this in the near future? It would be awesome to have this feature in a future release.

**Comment by BakasuraRCE** [comment]
@amalmurali47 @csomh Done :D

**Comment by aminvakil** [comment]
Although I'm not sure about `hexchat/hexchat` policy, whether they accept a PR with a merge commit in it or not.

Disclaimer: I have not seen any other PR from `hexchat/hexchat`, but I have seen this policy in other open-source projects.

**Pull request merged**
