### PR TITLE
dcc: Introduce dcc_type and dcc_state enums

### PR DESCRIPTION
**Pull request by bgamari**
Just a small refactoring.

### CODE REVIEW

**Comment by TingPing** [comment]
```c
dccgui.c: In function ‘dcc_dclick_cb’:
dccgui.c:710:2: warning: enumeration value ‘STAT_QUEUED’ not handled in switch [-Wswitch]
  switch (dcc->dccstat)
  ^~~~~~
dccgui.c:710:2: warning: enumeration value ‘STAT_ACTIVE’ not handled in switch [-Wswitch]
dccgui.c:710:2: warning: enumeration value ‘STAT_CONNECTING’ not handled in switch [-Wswitch]
```

**Comment by bgamari** [comment]
I've updated the branch; it seems I hadn't pushed the most recent
revision.

**Comment by TingPing** [comment]
The warning still remains.

**Comment by bgamari** [comment]
TingPing <notifications@github.com> writes:

> The warning still remains.
>
How about now? I'm afraid it's very hard for me to spot these warnings
from among the hundreds of others that already exist in the codebase.

**Comment by TingPing** [comment]
Building against gcc or clang should produce no warnings unless you are forcefully enabling more.

**Pull request closed without merging**
